version: "3"
services:
  minecraft-java-survival:
    image: itzg/minecraft-server:latest
    container_name: minecraft-java-survival
    restart: unless-stopped
    ports:
      - 25565:25565
    volumes:
      - /opt/minecraft:/data
    environment:
      EULA: "true"
      MODE: "survival"
      UID: 999
      GID: 993
      MEMORY: 2G
      DIFFICULTY: "peaceful"
      SERVER_NAME: "nukulartechniker.de"
      TYPE: "VANILLA"
      VERSION: "LATEST"
      FORGEVERSION: "RECOMMENDED"
      SPONGEBRANCH: "STABLE"
      FABRICVERSION: "LATEST"
      LEVEL: "world"
      PVP: "true"
      ENABLE_RCON: "false"
      RCON_PORT: "25575"
      RCON_PASSWORD: "minecraft"
      LEVEL_TYPE: "DEFAULT"
      SERVER_PORT: "25565"
      ONLINE_MODE: "true"
    stdin_open: true
    tty: true
